# Generated by Django 5.2.1 on 2026-04-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultryitems', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggseller',
            name='country',
            field=models.CharField(default='Ethiopia', max_length=100),
        ),
    ]
