# Generated by Django 5.2.1 on 2026-04-28 04:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poultryfarm', '0005_alter_item_main_image_alter_subimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='products/default.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='subimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='products/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
