# Generated by Django 5.2.1 on 2026-04-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultryfarm', '0008_remove_eggorder_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='products/main_images/'),
        ),
        migrations.AlterField(
            model_name='subimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/sub_images/'),
        ),
    ]
