# Generated by Django 5.2.1 on 2026-05-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultryfarm', '0009_alter_item_main_image_alter_subimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggseller',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
