# Generated by Django 5.2.1 on 2026-04-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_address_profile_city_profile_farm_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
    ]
