# Generated by Django 5.2.1 on 2026-04-30 04:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairyfarm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle',
            new_name='DairyProduct',
        ),
    ]
