# Generated by Django 5.2.1 on 2026-04-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyfarm', '0002_rename_vehicle_dairyfarm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
