# Generated by Django 5.2.1 on 2026-04-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultryitems', '0004_remove_chickenseller_breeds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='main_image',
            field=models.ImageField(blank=True, default='products/default.jpg', upload_to='upload_main_image/'),
        ),
        migrations.AlterField(
            model_name='subimage',
            name='image',
            field=models.ImageField(blank=True, default='products/default.jpg', upload_to='upload_sub_images/'),
        ),
    ]
