# Generated by Django 5.2.1 on 2026-04-28 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultryitems', '0007_alter_item_main_image_alter_subimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eggorder',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='eggorder',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='eggorder',
            name='customer_phone',
        ),
        migrations.AddField(
            model_name='eggorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='egg_orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eggorder',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
